# remote_theme: PfeifferChPT/pc-cdn-template
remote_theme: 4s-es/4ses-template
theme_color: '#f1f1f1'
footer_menu: footer_menu
hide_footer: true
author: PC-CDN 
since: 2019 #19.1.19
# Site Settings
lang: en
title: Four Stars Engineering Systems
tagline: Four Stars Engineering Systems (FourStars-ES)
email: 
description: German firm dedicated to providing engineering solutions for the PCB production sector including support of newly introduced test systems
baseurl: "/"
url: "https://4ses.pc-tests.tk/"
permalink: pretty
favicon: /assets/favicon/hosting1.png

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      image: /assets/img/bg/4ses.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "PC-CDN"
      layout: post
      image: /assets/img/bg/server1.jpg
      show_sidebar: false

markdown: kramdown
highlighter: rouge

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600/374758/?text=www.c-pfeiffer.de
    show_sidebar: false
    hero_image: /assets/img/bg/server2.jpg
