# remote_theme: PfeifferChPT/pc-cdn-template
remote_theme: 4s-es/4ses-template
theme_color: '#f0f5f0'
footer_menu: footer_menu
hide_footer: true
hide_share_buttons: true
author: FourStars-ES
since: 2009
# Site Settings
lang: en
title: Four Stars Engineering Systems
tagline: Four Stars Engineering Systems (FourStars-ES)
email: 
description: German firm dedicated to providing engineering solutions for the PCB production sector including support of newly introduced test systems
baseurl: "/"
url: "https://4ses.pc-tests.tk/"
permalink: pretty
favicon: /assets/favicon/hosting1.png

paginate: 5
paginate_path: "/news/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      hero_height: is-fullwidth
      show_sidebar: true
      image: /assets/img/bg/4ses.jpg
  -
    scope:
      path: "/news/"
      type: "posts"
    values:
      author: "4s-es"
      layout: post
      hero_height: is-fullwidth
      image: /assets/img/bg/4ses.jpg
      show_sidebar: true

markdown: kramdown
highlighter: rouge

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600/f0f5f0/?text=4stars-es.com
    show_sidebar: false
    hero_image: /assets/img/bg/4ses.jpg
